<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-10-14 14:44
=======
# Generated by Django 5.1.6 on 2025-10-15 12:54
>>>>>>> origin/hammm

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DfCafeFull",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "public_store_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "crawled_store_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("visit_time", models.CharField(blank=True, max_length=100, null=True)),
                ("rating", models.CharField(blank=True, max_length=20, null=True)),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("date", models.CharField(blank=True, max_length=20, null=True)),
                ("revisit", models.IntegerField(blank=True, null=True)),
                (
                    "visit_purpose",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("companion", models.CharField(blank=True, max_length=100, null=True)),
                ("tags", models.CharField(blank=True, max_length=255, null=True)),
                ("select_count", models.IntegerField(blank=True, null=True)),
                ("facilities", models.CharField(blank=True, max_length=255, null=True)),
                ("final_crawl_count", models.IntegerField(blank=True, null=True)),
                ("total_review_count", models.IntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("comfy_cafe", models.IntegerField(blank=True, null=True)),
                ("solo_cafe", models.IntegerField(blank=True, null=True)),
                ("book_cafe", models.IntegerField(blank=True, null=True)),
                ("unique_cafe", models.IntegerField(blank=True, null=True)),
                ("group_cafe", models.IntegerField(blank=True, null=True)),
                ("coffee_taste_cafe", models.IntegerField(blank=True, null=True)),
                ("study_cafe", models.IntegerField(blank=True, null=True)),
                ("bright_cafe", models.IntegerField(blank=True, null=True)),
                ("mood_cafe", models.IntegerField(blank=True, null=True)),
                ("dessert_taste_cafe", models.IntegerField(blank=True, null=True)),
                ("cheap_cafe", models.IntegerField(blank=True, null=True)),
                ("animal_cafe", models.IntegerField(blank=True, null=True)),
                ("night_cafe", models.IntegerField(blank=True, null=True)),
                ("hanok_cafe", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "df_cafe_full",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CafePhotoCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("place_id", models.CharField(blank=True, max_length=128, null=True)),
                ("photo_ref", models.CharField(blank=True, max_length=256, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
        ),
=======

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DfCafeFull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('crawled_store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_time', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('revisit', models.IntegerField(blank=True, null=True)),
                ('visit_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('companion', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('select_count', models.IntegerField(blank=True, null=True)),
                ('facilities', models.CharField(blank=True, max_length=255, null=True)),
                ('final_crawl_count', models.IntegerField(blank=True, null=True)),
                ('total_review_count', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('comfy_cafe', models.IntegerField(blank=True, null=True)),
                ('solo_cafe', models.IntegerField(blank=True, null=True)),
                ('book_cafe', models.IntegerField(blank=True, null=True)),
                ('unique_cafe', models.IntegerField(blank=True, null=True)),
                ('group_cafe', models.IntegerField(blank=True, null=True)),
                ('coffee_taste_cafe', models.IntegerField(blank=True, null=True)),
                ('study_cafe', models.IntegerField(blank=True, null=True)),
                ('bright_cafe', models.IntegerField(blank=True, null=True)),
                ('mood_cafe', models.IntegerField(blank=True, null=True)),
                ('dessert_taste_cafe', models.IntegerField(blank=True, null=True)),
                ('cheap_cafe', models.IntegerField(blank=True, null=True)),
                ('animal_cafe', models.IntegerField(blank=True, null=True)),
                ('night_cafe', models.IntegerField(blank=True, null=True)),
                ('hanok_cafe', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'df_cafe_full',
                'managed': False,
            },
        ),
>>>>>>> origin/hammm
    ]
