# Generated by Django 6.0 on 2026-01-05 05:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafes", "0002_alter_dfcafefull_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dfcafefull",
            options={},
        ),
    ]
