# Generated by Django 5.1.6 on 2025-06-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="place",
            name="name",
        ),
        migrations.AddField(
            model_name="place",
            name="companion",
            field=models.CharField(
                blank=True, db_column="동반자", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="content",
            field=models.TextField(blank=True, db_column="content", default=""),
        ),
        migrations.AddField(
            model_name="place",
            name="convenience",
            field=models.CharField(
                blank=True, db_column="편의시설", default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="crawling_name",
            field=models.CharField(
                blank=True, db_column="크롤링 가게명", default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="date",
            field=models.CharField(
                blank=True, db_column="date", default="", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="purpose",
            field=models.CharField(
                blank=True, db_column="방문목적", default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="rating",
            field=models.CharField(
                blank=True, db_column="평점", default="", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="revisit",
            field=models.CharField(
                blank=True, db_column="revisit", default="", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="selection_count",
            field=models.IntegerField(db_column="선택 수", default=0),
        ),
        migrations.AddField(
            model_name="place",
            name="source",
            field=models.CharField(
                blank=True, db_column="출처", default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="tags",
            field=models.CharField(
                blank=True, db_column="태그", default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="time",
            field=models.CharField(
                blank=True, db_column="시간", default="", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="category",
            field=models.CharField(
                blank=True, db_column="카테고리", default="", max_length=100
            ),
        ),
    ]
