# Generated by Django 5.1.6 on 2025-11-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_faqpost_myuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqpost",
            name="answer",
            field=models.TextField(blank=True),
        ),
    ]
