# Generated by Django 5.1.6 on 2025-11-10 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_faqpost_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="app.faqpost",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
