# Generated by Django 5.1.6 on 2025-11-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_faqcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqcomment",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
