# Generated by Django 5.1.6 on 2025-11-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_faqcomment_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="user_id",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
