"""
Django settings for seoseong_ida project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d&uzo+u&x-cdki#9xa@%_o1gtbs7jvm^fd90mdh5a_8c%-%b^4'
NAVER_MAPS_CLIENT_ID = "dkm4t7wo8m"
# GOOGLE_API_KEY = "AIzaSyA6rJZ9AoW5bSYQnRcswMc_OTFwojIJPUg"
GOOGLE_API_KEY = "AIzaSyAjldbFc9cYRuQ48xDdjlle4jDANLLqB14"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    "cafes",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.middleware.CrossOriginOpenerPolicyMiddleware',
]

ROOT_URLCONF = 'seoseong_ida.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'app/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
                'seoseong_ida.context_processors.naver_maps',
                'seoseong_ida.context_processors.google_maps',
            ],
        },
    },
]

WSGI_APPLICATION = 'seoseong_ida.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'myproject_db',
        'USER': 'myuser',
        'PASSWORD': '0000',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET NAMES 'utf8mb4'"
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'app.MyUser'

# FIREBASE_CREDENTIAL_PATH = os.path.join(BASE_DIR, "firebase_key.json")



import os
import firebase_admin
from firebase_admin import credentials

# ─────────────────────────────────────────────
# 🔥 Firebase Admin SDK 초기화
# ─────────────────────────────────────────────
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 서비스 계정 JSON 절대 경로 설정
FIREBASE_CREDENTIAL_PATH = os.path.join(BASE_DIR, "firebase_key.json")
FIREBASE_CONFIG = {
    'apiKey': "AIzaSyCeVley_bZxtGzVk2rqIARIWGi6M9JEbf4",
    'authDomain': "seoseongida.firebaseapp.com",
    'projectId': "seoseongida",
    'storageBucket': "seoseongida.firebasestorage.app",
    'messagingSenderId': "891598444138",
    'appId': "1:891598444138:web:529fe607ab00484be25c13",
}

# Firebase 앱 초기화 (한 번만)
if not firebase_admin._apps:
    if os.path.exists(FIREBASE_CREDENTIAL_PATH):
        cred = credentials.Certificate(FIREBASE_CREDENTIAL_PATH)
        firebase_admin.initialize_app(cred)
        print("🔥 Firebase Admin SDK initialized successfully!")
    else:
        raise RuntimeError(f"Firebase credential file not found: {FIREBASE_CREDENTIAL_PATH}")

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home" 

TIME_ZONE = "Asia/Seoul"
USE_TZ = True